# Generated by Django 5.1.1 on 2024-10-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='category',
            field=models.CharField(choices=[('INFO', 'Информация'), ('WARNING', 'Предупреждение'), ('ERROR', 'Ошибка'), ('DEBUG', 'Отладка')], max_length=64),
        ),
        migrations.AlterField(
            model_name='logentry',
            name='user',
            field=models.CharField(max_length=384),
        ),
    ]
