# Generated by Django 5.1.1 on 2024-10-06 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_alter_logentry_category_alter_logentry_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='category',
            field=models.CharField(max_length=64),
        ),
    ]
